// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List upcoming or recent RaagConnect concerts and events, optionally filtered by title or location.",
  inputSchema: {
    search: z.string().optional().describe("Filter by text in the event title."),
    upcoming_only: z.boolean().optional().describe("Only return events on or after today. Defaults to true."),
    limit: z.number().int().optional().describe("Maximum number of events to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("events").select("id, title, date, time, location_name, price, notes, artist_id").order("date", { ascending: true }).limit(max);
    if (upcoming_only !== false) {
      query = query.gte("date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    }
    if (search?.trim()) query = query.ilike("title", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get full details for one RaagConnect event by its id, including performing artist and schedule.",
  inputSchema: { event_id: z2.string().describe("The event id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: event, error } = await supabase.from("events").select("*").eq("id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!event) return { content: [{ type: "text", text: "Event not found" }], isError: true };
    const { data: schedule } = await supabase.from("event_schedule").select("*").eq("event_id", event_id);
    const result = { ...event, schedule: schedule ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { event: result }
    };
  }
});

// src/lib/mcp/tools/create-event.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_event_default = defineTool3({
  name: "create_event",
  title: "Create event",
  description: "Create a new concert or event on RaagConnect owned by the signed-in user.",
  inputSchema: {
    title: z3.string().describe("Event title."),
    date: z3.string().describe("Event date in YYYY-MM-DD format."),
    time: z3.string().describe("Event start time in HH:MM 24-hour format."),
    location_name: z3.string().optional().describe("Venue or location name."),
    price: z3.number().optional().describe("Ticket price."),
    notes: z3.string().optional().describe("Additional details about the event."),
    artist_id: z3.string().optional().describe("Id of the performing artist profile.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      date: input.date,
      time: input.time,
      location_name: input.location_name ?? null,
      price: input.price ?? null,
      notes: input.notes ?? null,
      artist_id: input.artist_id ?? null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/list-artists.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_artists_default = defineTool4({
  name: "list_artists",
  title: "List artists",
  description: "List RaagConnect artist profiles, optionally filtered by name or genre.",
  inputSchema: {
    search: z4.string().optional().describe("Filter by text in the artist name."),
    genre: z4.string().optional().describe("Filter by genre."),
    limit: z4.number().int().optional().describe("Maximum number of artists to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, genre, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("artists").select("id, name, genre, bio, location_name").order("name", { ascending: true }).limit(max);
    if (search?.trim()) query = query.ilike("name", `%${search.trim()}%`);
    if (genre?.trim()) query = query.ilike("genre", `%${genre.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { artists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-classes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_classes_default = defineTool5({
  name: "list_classes",
  title: "List classes",
  description: "List RaagConnect music classes, optionally filtered by title, genre, or skill level.",
  inputSchema: {
    search: z5.string().optional().describe("Filter by text in the class title."),
    genre: z5.string().optional().describe("Filter by genre."),
    skill_level: z5.string().optional().describe("Filter by skill level, e.g. beginner or advanced."),
    limit: z5.number().int().optional().describe("Maximum number of classes to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, genre, skill_level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("classes").select("id, title, genre, skill_level, class_mode, class_type, price, location_name, schedule_details, description").order("title", { ascending: true }).limit(max);
    if (search?.trim()) query = query.ilike("title", `%${search.trim()}%`);
    if (genre?.trim()) query = query.ilike("genre", `%${genre.trim()}%`);
    if (skill_level?.trim()) query = query.ilike("skill_level", `%${skill_level.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-bookings.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var my_bookings_default = defineTool6({
  name: "my_bookings",
  title: "My bookings",
  description: "List the signed-in user's event and class bookings on RaagConnect.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: eventBookings, error: eventError } = await supabase.from("bookings").select("id, event_id, attendee_name, attendee_email, amount, status, payment_method, created_at").eq("user_id", userId).order("created_at", { ascending: false });
    if (eventError) return { content: [{ type: "text", text: eventError.message }], isError: true };
    const { data: classBookings, error: classError } = await supabase.from("class_bookings").select("*").eq("user_id", userId).order("created_at", { ascending: false });
    if (classError) return { content: [{ type: "text", text: classError.message }], isError: true };
    const result = { event_bookings: eventBookings ?? [], class_bookings: classBookings ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var search_knowledge_default = defineTool7({
  name: "search_knowledge",
  title: "Search knowledge posts",
  description: "Search RaagConnect knowledge posts about Hindustani classical music by title, content, or category.",
  inputSchema: {
    query: z6.string().optional().describe("Text to search for in post titles and content."),
    category: z6.string().optional().describe("Filter by category (e.g. dhrupad-dhamaar, chota-bada-khayal, kayada-rela, tabla-gat-tukda-paran, jhod-jhala, sitar-sarod-gat, history-theory, other)."),
    limit: z6.number().int().optional().describe("Maximum number of posts to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 10, 1), 50);
    let builder = supabase.from("knowledge_posts").select("id, title, content, category, created_at").order("created_at", { ascending: false }).limit(max);
    const q = query?.trim();
    if (q) builder = builder.or(`title.ilike.%${q}%,content.ilike.%${q}%`);
    if (category?.trim()) builder = builder.ilike("category", `%${category.trim()}%`);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sjwtmymfdtirwrycneup";
var mcp_default = defineMcp({
  name: "raagconnect",
  title: "RaagConnect",
  version: "0.1.0",
  instructions: "Tools for RaagConnect, a platform for Hindustani classical music concerts, artists, and classes. Use `list_events` and `get_event` for concerts, `create_event` to add one, `list_artists` and `list_classes` for discovery, `my_bookings` for the signed-in user's bookings, and `search_knowledge` for music knowledge posts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, create_event_default, list_artists_default, list_classes_default, my_bookings_default, search_knowledge_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
